"""
Random Search (Latin Hypercube Sampling)
=========================================

Entry point for running a random hyperparameter search with Optuna,
using Latin Hypercube Sampling (LHS) for better coverage of the
search space.

Usage (from the project root):
    python -m OptunaTuning.random_search

What this does:
  1. Loads the preprocessed dataset
  2. Generates N configurations via LHS (evenly spread across all
     parameter ranges — much better than plain random for high-dim spaces)
  3. Enqueues them into an Optuna study (no pruning — every trial
     runs all epochs so we get full learning curves)
  4. Runs the study and saves results to OptunaTuning/results/random_search_{log_name}/

The purpose is to get full learning curves for a diverse set of
configurations, so you can inspect them and pick a good grace period
for Hyperband pruning in the main TPE-based optimization.

The study is stored in a SQLite database, so if the script crashes
or is interrupted, you can re-run it and it will resume from where
it left off.
"""

import os
import pickle

import optuna

from OptunaTuning.config import RANDOM_SEARCH_CONFIG, DATASET_CONFIG
from OptunaTuning.objective import create_objective
from OptunaTuning.utils import load_data, generate_lhs_configurations, save_results_csv


def main():
    # ── Configuration ──
    log_name = DATASET_CONFIG["log_name"]
    n_trials = RANDOM_SEARCH_CONFIG["n_trials"]
    n_epochs = RANDOM_SEARCH_CONFIG["n_epochs"]
    seed = RANDOM_SEARCH_CONFIG["seed"]

    # ── Output directory ──
    results_dir = os.path.join("OptunaTuning", "results", f"random_search_{log_name}")
    os.makedirs(results_dir, exist_ok=True)

    # ── Load data (done once, shared across all trials) ──
    print(f"Loading data for '{log_name}'...")
    data = load_data(log_name)
    print(f"  {data['num_activities']} activities, "
          f"{len(data['train_dataset'])} training instances")

    # ── Create the Optuna study ──
    #
    # We use a RandomSampler as a fallback, but it won't actually be
    # used — all trials are pre-generated by LHS and enqueued.
    #
    # NopPruner (No-Operation Pruner): no early stopping. Every trial
    #   runs all n_epochs. This is intentional — we want full learning
    #   curves so we can decide on a good grace period for Hyperband.
    #
    # storage: SQLite file. Enables resumability + later inspection.
    #
    storage_path = os.path.join(results_dir, "random_search_study.db")
    storage_url = f"sqlite:///{storage_path}"

    study = optuna.create_study(
        study_name="sutran_random_search",
        direction="minimize",          # lower val_loss = better
        sampler=optuna.samplers.RandomSampler(seed=seed),
        pruner=optuna.pruners.NopPruner(),
        storage=storage_url,
        load_if_exists=True,
    )

    # ── How many trials are already done? (for resumability) ──
    n_complete = len([
        t for t in study.trials
        if t.state == optuna.trial.TrialState.COMPLETE
    ])
    n_remaining = max(0, n_trials - n_complete)

    if n_complete > 0:
        print(f"  Resuming: {n_complete} trials already complete, "
              f"{n_remaining} remaining.")
    else:
        print(f"  Starting fresh: {n_trials} trials, {n_epochs} epochs each.")

    if n_remaining == 0:
        print("  All trials already complete. Nothing to do.")
    else:
        # ── Generate LHS configurations and enqueue them ──
        # LHS pre-generates all configurations upfront, ensuring each
        # parameter range is evenly covered. We then tell Optuna
        # "use exactly these values" via enqueue_trial().
        #
        # We generate all n_trials configs (not just n_remaining) so
        # that the LHS design is deterministic regardless of resuming.
        # Already-completed configs will simply be skipped by Optuna
        # since enqueue_trial only affects the *next* trial.
        lhs_configs = generate_lhs_configurations(n_trials, seed=seed)
        print(f"  Generated {len(lhs_configs)} LHS configurations.")

        # Only enqueue the ones we haven't run yet.
        for config in lhs_configs[n_complete:]:
            study.enqueue_trial(config)

        # ── Create objective + results collector ──
        results_collector = {}
        objective = create_objective(data, n_epochs, results_collector)

        # ── Run the search ──
        study.optimize(objective, n_trials=n_remaining)

        # ── Save results ──
        results_path = os.path.join(results_dir, "random_search_results.pkl")
        with open(results_path, "wb") as f:
            pickle.dump(results_collector, f)
        print(f"  Trial results saved to {results_path}")

        csv_path = os.path.join(results_dir, "random_search_results.csv")
        save_results_csv(results_collector, csv_path)

    # ── Print summary ──
    print("\n" + "=" * 60)
    print("RANDOM SEARCH COMPLETE")
    print("=" * 60)

    # Sort trials by objective value (best first)
    completed_trials = [
        t for t in study.trials
        if t.state == optuna.trial.TrialState.COMPLETE
    ]
    completed_trials.sort(key=lambda t: t.value)

    for i, trial in enumerate(completed_trials):
        print(f"  #{i+1}  Trial {trial.number:>3d}  "
              f"val_loss={trial.value:.4f}  "
              f"d_model={trial.params['d_model']:>3d}  "
              f"d_ff_mult={trial.params['d_ff_multiplier']}  "
              f"enc={trial.params['num_prefix_encoder_layers']}  "
              f"dec={trial.params['num_decoder_layers']}  "
              f"heads={trial.params['num_heads']:>2d}  "
              f"lr={trial.params['learning_rate']:.2e}  "
              f"wd={trial.params['weight_decay']:.2e}  "
              f"drop={trial.params['dropout']:.2f}")

    print(f"\nBest trial: #{study.best_trial.number} "
          f"with val_loss={study.best_value:.4f}")
    print(f"Best params: {study.best_params}")
    print(f"\nStudy database: {storage_path}")
    print(f"To inspect later:  optuna.load_study("
          f"'sutran_random_search', storage='{storage_url}')")


if __name__ == "__main__":
    main()
